## Select profile
spring:
  profiles:
    active: @activatedProperties@
  application:
    name: pres
  cloud:
    vault:
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      scheme: http
      host: localhost
      port: 8200
      kv:
        enabled: true
        backend: vaultdemo
